jobs:
  build:
    docker:
      - image: 'node:16.14.0'
    steps:
      - checkout
      - sonarcloud/scan
orbs:
#changed version@1.4.0 ti 2.0.0 java17 enabled support
  sonarcloud: sonarsource/sonarcloud@2.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
