jobs:
  build:
    docker:
      - image: 'node:16.14.0'
    steps:
      - checkout
      - sonarcloud/scan
orbs:

  sonarcloud: sonarsource/sonarcloud@2.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
