-- MySQL Script generated by MySQL Workbench
-- mar 21 nov 2023, 15:12:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ISPW
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ISPW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ISPW` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ISPW` ;

-- -----------------------------------------------------
-- Table `ISPW`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`USERS` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `idRuolo` VARCHAR(1) NOT NULL DEFAULT 'U',
  `Nome` VARCHAR(40) NULL DEFAULT NULL,
  `Cognome` VARCHAR(40) NULL DEFAULT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `pwd` VARCHAR(16) NULL DEFAULT NULL,
  `descrizione` TEXT NULL DEFAULT NULL,
  `DataDiNascita` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`AMMINISTRATORE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`AMMINISTRATORE` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idAdmin`),
  INDEX `idUser` (`idUser` ASC) VISIBLE,
  CONSTRAINT `AMMINISTRATORE_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `ISPW`.`USERS` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`CARTACREDITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`CARTACREDITO` (
  `nomeP` VARCHAR(10) NULL DEFAULT NULL,
  `cognomeP` VARCHAR(20) NULL DEFAULT NULL,
  `codiceCarta` VARCHAR(20) NULL DEFAULT NULL,
  `scad` DATE NULL DEFAULT NULL,
  `codicePin` VARCHAR(5) NULL DEFAULT NULL,
  `ammontare` FLOAT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`EDITORE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`EDITORE` (
  `idEditor` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL DEFAULT NULL,
  `casaEditrice` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`idEditor`),
  INDEX `idUser` (`idUser` ASC) VISIBLE,
  CONSTRAINT `EDITORE_ibfk_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `ISPW`.`USERS` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`FATTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`FATTURA` (
  `nome` VARCHAR(10) NULL DEFAULT NULL,
  `cognome` VARCHAR(10) NULL DEFAULT NULL,
  `via` VARCHAR(50) NULL DEFAULT NULL,
  `comunicazoni` TEXT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `ammontare` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`GIORNALE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`GIORNALE` (
  `titolo` VARCHAR(200) NULL DEFAULT NULL,
  `tipologia` VARCHAR(60) NULL DEFAULT NULL,
  `lingua` VARCHAR(30) NULL DEFAULT NULL,
  `editore` VARCHAR(200) NULL DEFAULT NULL,
  `dataPubblicazione` DATE NULL DEFAULT NULL,
  `copiRim` INT NULL DEFAULT NULL,
  `disp` INT NULL DEFAULT NULL,
  `prezzo` FLOAT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`LIBRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`LIBRO` (
  `titolo` VARCHAR(200) NULL DEFAULT NULL,
  `numeroPagine` INT NULL DEFAULT NULL,
  `Cod_isbn` VARCHAR(10) NOT NULL,
  `editore` VARCHAR(200) NULL DEFAULT NULL,
  `autore` VARCHAR(200) NULL DEFAULT NULL,
  `lingua` VARCHAR(10) NULL DEFAULT NULL,
  `categoria` VARCHAR(60) NULL DEFAULT NULL,
  `dataPubblicazione` DATE NULL DEFAULT NULL,
  `recensione` TEXT NULL DEFAULT NULL,
  `copieVendute` INT NULL DEFAULT NULL,
  `breveDescrizione` TEXT NULL DEFAULT NULL,
  `disp` INT NULL DEFAULT NULL,
  `prezzo` FLOAT NULL DEFAULT NULL,
  `copieRimanenti` INT NULL DEFAULT NULL,
  `idProd` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idProd`),
  UNIQUE INDEX `Cod_isbn` (`Cod_isbn` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`NEGOZIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`NEGOZIO` (
  `idNegozio` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `via` VARCHAR(100) NULL DEFAULT NULL,
  `isValid` TINYINT(1) NULL DEFAULT NULL,
  `isOpen` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idNegozio`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`PAGAMENTO` (
  `id_op` INT NOT NULL AUTO_INCREMENT,
  `metodo` VARCHAR(10) NULL DEFAULT NULL,
  `esito` INT NULL DEFAULT NULL,
  `nomeUtente` VARCHAR(10) NULL DEFAULT NULL,
  `spesaTotale` FLOAT NULL DEFAULT NULL,
  `eMail` VARCHAR(100) NULL DEFAULT NULL,
  `tipoAcquisto` VARCHAR(20) NULL DEFAULT NULL,
  `idProd` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_op`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`RIVISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`RIVISTA` (
  `titolo` VARCHAR(200) NULL DEFAULT NULL,
  `tipologia` VARCHAR(60) NULL DEFAULT NULL,
  `autore` VARCHAR(200) NULL DEFAULT NULL,
  `lingua` VARCHAR(10) NULL DEFAULT NULL,
  `editore` VARCHAR(200) NULL DEFAULT NULL,
  `Descrizione` TEXT NULL DEFAULT NULL,
  `dataPubblicazione` DATE NULL DEFAULT NULL,
  `disp` INT NULL DEFAULT NULL,
  `prezzo` FLOAT NULL DEFAULT NULL,
  `copieRimanenti` INT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ISPW`.`SCRITTORI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ISPW`.`SCRITTORI` (
  `idScrittore` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL DEFAULT NULL,
  `editoreAssociato` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idScrittore`),
  INDEX `editoreAssociato` (`editoreAssociato` ASC) VISIBLE,
  INDEX `idUser` (`idUser` ASC) VISIBLE,
  CONSTRAINT `SCRITTORI_ibfk_1`
    FOREIGN KEY (`editoreAssociato`)
    REFERENCES `ISPW`.`EDITORE` (`idEditor`),
  CONSTRAINT `SCRITTORI_ibfk_2`
    FOREIGN KEY (`idUser`)
    REFERENCES `ISPW`.`USERS` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


START TRANSACTION;
USE `ISPW`;
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Apocalypse town: Cronache dalla fine della civilta urbana', 239, '0000000001', 'Laterza', 'Alessandro Coppola', 'italiano', 'LIBRI_UNIVERSITARI', '2012-05-18', 'urbanistica della contemporaneita :Il libro esplora una condizione limite delle citta americane nella decrescita, aprendo una prospettiva ed una riflessione sul futuro prossimo del territorio urbano europeo.Da leggere assolutamente \',600,\'Dalle praterie urbane di Youngstown, dove la amministrazione comunale si e ormai ridotta a pianificare con zelo la autodistruzione della citta, alla industria del riciclo e della decostruzione di Buffalo, nella quale attivisti visionari smontano con dovizia e con amore cio  che resta della citta ; dai deserti alimentari di Detroit e Philadelphia, dove sono scomparsi negozi e supermercati e gli abitanti si organizzano con geniali intraprese agricole', 600, 'Dalle praterie urbane di Youngstown, dove la amministrazione comunale si e ormai ridotta a pianificare con zelo la autodistruzione della citta, alla industria del riciclo e della decostruzione di Buffalo, nella quale attivisti visionari smontano con dovizia e con amore cio  che resta della citta ; dai deserti alimentari di Detroit e Philadelphia, dove sono scomparsi negozi e supermercati e gli abitanti si organizzano con geniali intraprese agricole', 1, 7.99, 5571, 1);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Andrea Baranes : control i falsi miti', 150, '0000000002', 'Laterza', 'Andra Baranes', 'italiano', 'ECONOMIA', '2014-03-01', 'Contro i falsi miti : Andrea Baranes spiega con semplicita perchè quello dei mercati è un falso problema. Un libro agile e compresibile a tutti.', 100, 'Oggi la speculazione domina la finanza. La finanza controlla la ECONOMIA. La ECONOMIA determina le scelte politiche. La politica impatta sulla vita delle persone. Quello che dobbiamo fare è semplicemente ribaltare la attuale scala di valori e leggere al contrario le frasi precedenti.', 1, 5.99, 540, 2);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Il libro dello splendore', 102, '8877107324', 'SE', 'Ariel Toaff', 'italiano', 'LETTERATURA_NARRATIVA', '2008-02-28', 'Un libretto utilissimo : Leggere questo libro per me che mi sto avvicinando alla Cabala è stato davvero importante. La prefazione di Elio Toaff è straordinaria e capisco anche la grandezza di questo rabbino nei decenni scorsi. Premetto che io non sono di religione ebraica ma proprio questo libro mi ha introdotto dentro una filosofia veramente fondamentale.', 500, 'Il testo classico della Cabbala è lo Zohar (II libro dello splendore), per secoli considerato sacro alla religione ebraica e ancor oggi venerato nei circoli mistici, al pari della Bibbia e del Talmud. Attribuito dai cabbalisti a Rabbi Shim on bar Yochai, celebre dottore della Mishna, e ambientato nella Palestina della seconda meta del II secolo dell era volgare.', 1, 14.90, 48, 3);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Come i servizi segreti usano i media', 240, '0000000003', 'Ponte alle grazie', 'Aldo Giannuli', 'italiano', 'LETTERATURA_NARRATIVA', '2012-11-22', 'Male: Nonostante lo avessi trovato inutilmente lungo, non mi era dispiaciuto il precedente libro di Giannuli Come funzionano i servizi segreti. Con questo volume invece non posso che segnalare un notevole passo indietro dell autore. Il capitolo dedicato all OSINT, che dovrebbe costituire il cuore del libro, e decisamente scarso e per fonti utilizzate (il tutto si basa quasi esclusivamente su un singolo documento tecnico NATO datato 2002!) e per capacita di comprensione dell autore, la quale appare oltremodo limitata (non da fondamentalmente mai la idea di capire cosa sia effettivamente lo OSINT e oserei dire  in generale la attivita di intelligence). Davvero terribili, cosi come nel volume precedente, tutti i riferimenti fatti alla tecnologia per la intelligence. Inutile ed assolutamente campata per aria la sezione conclusiva Brioche, cappuccino e intelligence, che sembra soltanto un modo con il quale l autore riesce a riciclare materiale preparato in altre sedi. Insomma, lettura decisamente deludente.', 40, 'Dopo il grande successo di Come funzionano i servizi segreti, Aldo Giannuli torna a scrivere d’intelligence, affrontando uno degli aspetti meno conosciuti e piu controversi dell’attivita dei servizi: il modo in cui manipolano e utilizzano l’informazione.', 1, 6.49, 100, 4);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Sulla verità', 180, '0000000004', 'Laterza', 'Donand Davidson', 'italiano', 'LETTERATURA_NARRATIVA', '1705-01-01', 'NO', 4, '', 0, 41.00, 0, 5);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Erasgon Vol 1', 562, '8817061622', 'Rizzoli', 'Christopher Paolini', 'italiano', 'FANTASCIENZA_FANTASY', '2012-10-03', 'Ottimo inizio: Il libro e arrivato nei tempi previsti ed in ottime condizioni. Come si puo leggere anche sulla presentazione, il libro e stato scritto quando l autore aveva 15 anni, fattore che si nota subito. Ha uno stile ancora immaturo, poco sviluppato nei dialoghi e nelle descrizioni.\nNonostante cio, la lettura e scorrevole e interessante per chi ama il genere.', 40000, 'Quando Eragon trova una liscia pietra blu nella foresta, è convinto che gli sia toccata una grande fortuna: potra venderla e nutrire la sua famiglia per tutta òa stagione fredda. Ma la pietra in realta e un uovo. Quando si schiude rivelando il suo straordinario contenuto, un cucciolo di drago, Eragon scopre che gli e toccato in sorte una eredita antica come Impero. Forte di una spada magica e dei consigli di un vecchio cantastorie, dovra cavarsela in un universo denso di magia, mistero e insidie, imparare a distinguere amico dal nemico, dimostrare di essere il degno erede dei Cavalieri dei Draghi.', 1, 12.00, 1000, 6);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Scritti inediti di linguistica generale', 146, '8842068276', 'Laterza', 'Ferdinand de Saussure', 'italiano', 'LINGUISTICA_SCRITTURA', '2005-04-14', '', 0, '', 0, 0, 0, 7);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Alchimia e kabbalah', 107, '8867231553', 'SE', 'Alchimia e kabbalah', 'italiano', 'ALTRO', '2012-07-02', '', 100, '', 1, 17.00, 40, 8);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('EXCEL le 10 cose che devi conoscere del foglio elettronico', 61, '1520510888', 'Independently published', 'Giampietro Lanzanova', 'italiano', 'INFORMATICA', '2017-02-02', 'Utile compendio : Utile compendio per chi non e molto pratico di excel. Ho comprato anche il libro seguente e non me ne sono pentita. Certo, per maggiori approfondimenti forse serve un corso piu ampio', 40, 'Il percorso formativo dell’apprendimento in genere e sempre piuttosto lungo, ma andare subito al sodo della questione puo consentire di fare un salto qualitativo rapido delle proprie conoscenze, ed e proprio lo scopo di questo libro', 1, 9.99, 500, 9);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Dungeons & Dragons - 5a Edizione - Manuale del Giocatore', 315, '0000000005', 'Asmodee', 'Wizard of the coast', 'italiano', 'ALTRO', '2018-01-01', 'Ottimo Manuale: Ottimo manuale per chi vuole iniziare a giocare di ruolo', 23000, '', 1, 45, 1000, 10);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Grammatica italiana', 123, '0000000006', 'Garzanti', 'Redazioni garzanti', 'italiano', 'ALTRO', '2012-10-31', '', 550, '', 1, 5.0, 40000, 11);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Kobane calling. Oggi:', 312, '8832734591', 'Bao publishing', 'Zerocalcare', 'italiano', 'FUMETTI_MANGA', '2020-05-14', 'assurdo', 2000, 'compralo', 1, 22.0, 10, 12);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('A babbo morto. Una storia di Natale ', 0, '8832735512', 'Bao Publishing', 'Zerocalcare', 'italiano', 'FUMETTI_MANGA', '2020-11-12', 'ottimo', 100, 'compralo', 1, 11.00, 10, 13);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Scheletri', 240, '8832734893', 'Bao Publishing', 'Zerocalcare', 'italiano', 'FUMETTI_MANGA', '2020-10-15', 'ottimo', 1000, 'compralo', 1, 20.00, 15, 14);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('La scuola di pizze in faccia del professor Calcare', 298, '8832733250', 'Bao Publishing', 'Zerocalcare', 'italiano', 'FUMETTI_MANGA', '2019-10-21', 'ottimo', 1070, 'compralo', 2, 20.00, 48, 15);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Dodici', 95, '8865431806', 'Bao Publishing', 'Zerocalcare', 'italiano', 'FUMETTI_MANGA', '2013-10-17', 'ottimo', 1000, 'compralo', 1, 11.00, 11, 16);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('Tecniche proibite di persuasione, manipolazione e influenza utilizzando schemi di linguaggio e tecniche di PNL', 226, '1722235608', 'CreateSpace Independent Publishing Platform', 'Zerocalcare', 'italiano', 'FUMETTI_MANGA', '2018-07-01', 'ottimo', 1000, 'compralo se vuoi vivere da re', 1, 15.40, 3, 17);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('CiccioGamer89 Presenta Fortnite. Trucchi e Segreti', 135, '8893675056', 'Magazzini salani', 'CiccioGamer89', 'italiano', 'COMPUTER_GIOCHI', '2018-09-27', 'evita dai', 10, 'non comprarlo', 1, 11.00, 2, 18);
INSERT INTO `ISPW`.`LIBRO` (`titolo`, `numeroPagine`, `Cod_isbn`, `editore`, `autore`, `lingua`, `categoria`, `dataPubblicazione`, `recensione`, `copieVendute`, `breveDescrizione`, `disp`, `prezzo`, `copieRimanenti`, `idProd`) VALUES ('In cucina con Ciccio', 120, '8893678683', 'Magazzini salani', 'CiccioGamer89', 'italiano', 'FUMETTI_MANGA', '2013-10-17', 'non malvagio', 1, 'prova nuove ricette', 1, 16.50, 20, 19);

COMMIT;
-- -----------------------------------------------------
-- Data for table `ISPW`.`USERS`
-- -----------------------------------------------------
START TRANSACTION;
USE `ISPW`;
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (1, 'A', 'admin', 'admin', 'admin@admin.com', 'Admin871', 'utente \"admin\"', '1980-10-26');
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (2, 'A', 'Gianni', 'Morandi', 'giannni@gmail.com', 'BigHand21', 'utente con privilegi massimi', '1940-10-18');
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (3, 'U', 'Gino', 'Zaia', 'gino@zaia.eu', '25041995Gz', 'utente semplice', '1995-04-25');
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (4, 'U', 'Giulia', 'Conforto', 'giuliaConforto@gmail.eu', '12345678Gc', 'utente semplice', '1998-09-05');
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (5, 'W', 'Zerocalcare', 'Zerocalcare', 'zerocalcare@gmail.com', 'Zerocalcare21', 'scrittore semplice', '1980-05-20');
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (6, 'E', 'Bao Publishing', 'Bao Publishing', 'baoPublishing@gmail.com', 'BaoPub2021', 'editore semplice', '1960-11-21');
INSERT INTO `ISPW`.`USERS` (`idUser`, `idRuolo`, `Nome`, `Cognome`, `Email`, `pwd`, `descrizione`, `DataDiNascita`) VALUES (7, 'U', 'foo user', 'foo user', 'userfoo152@gmail.com', 'foo15us', 'utente foo', '2000-01-05');


COMMIT;


-- -----------------------------------------------------
-- Data for table `ISPW`.`GIORNALE`
-- -----------------------------------------------------
START TRANSACTION;
USE `ISPW`;
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La Republica1', 'QUOTIDIANO', 'italiano', 'La Republica', '2021-01-31', 5, 1, 2.0, 1);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La Republica2', 'QUOTIDIANO', 'italiano', 'La Republica', '2021-01-30', 0, 0, 2.0, 2);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La Republica3', 'QUOTIDIANO', 'italiano', 'La Republica', '2021-02-01', 10, 1, 2.0, 3);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La Republica4', 'QUOTIDIANO', 'italiano', 'La Republica', '2021-02-02', 14, 1, 2.0, 4);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La Republica5', 'QUOTIDIANO', 'italiano', 'La Republica', '2021-02-03', 10, 1, 2.0, 5);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La Republica6', 'QUOTIDIANO', 'italiano', 'La Republica', '2021-02-04', 15, 1, 2.0, 6);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('Il Fatto Quotidiano1', 'QUOTIDIANO', 'italiano', 'Il Fatto Quotidiano', '2021-01-31', 0, 0, 2.0, 7);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('Il Fatto Quotidiano2', 'QUOTIDIANO', 'italiano', 'Il Fatto Quotidiano', '2021-01-30', 0, 0, 2.0, 8);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('Il Fatto Quotidiano3', 'QUOTIDIANO', 'italiano', 'Il Fatto Quotidiano', '2021-02-01', 0, 0, 2.0, 9);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('Il Fatto Quotidiano4', 'QUOTIDIANO', 'italiano', 'Il Fatto Quotidiano', '2021-02-02', 15, 1, 2.0, 10);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('Il Fatto Quotidiano5', 'QUOTIDIANO', 'italiano', 'Il Fatto Quotidiano', '2021-02-03', 16, 1, 2.0, 11);
INSERT INTO `ISPW`.`GIORNALE` (`titolo`, `tipologia`, `lingua`, `editore`, `dataPubblicazione`, `copiRim`, `disp`, `prezzo`, `id`) VALUES ('La gazzetta del profeta', 'QUOTIDIANO', 'italiano', 'Hoepli', '2022-05-05', 20, 1, 0.85, 12);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ISPW`.`NEGOZIO`
-- -----------------------------------------------------
START TRANSACTION;
USE `ISPW`;
INSERT INTO `ISPW`.`NEGOZIO` (`idNegozio`, `nome`, `via`, `isValid`, `isOpen`) VALUES (1, 'Negozio A', 'via A', true, false);
INSERT INTO `ISPW`.`NEGOZIO` (`idNegozio`, `nome`, `via`, `isValid`, `isOpen`) VALUES (2, 'Negozio B', 'via B', true, true);
INSERT INTO `ISPW`.`NEGOZIO` (`idNegozio`, `nome`, `via`, `isValid`, `isOpen`) VALUES (3, 'Negozio C', 'via C', false, true);
INSERT INTO `ISPW`.`NEGOZIO` (`idNegozio`, `nome`, `via`, `isValid`, `isOpen`) VALUES (4, 'Negozio D', 'via D', false, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `ISPW`.`RIVISTA`
-- -----------------------------------------------------
START TRANSACTION;
USE `ISPW`;
INSERT INTO `ISPW`.`RIVISTA` (`titolo`, `tipologia`, `autore`, `lingua`, `editore`, `Descrizione`, `dataPubblicazione`, `disp`, `prezzo`, `copieRimanenti`, `id`) VALUES ('Focus', 'MENSILE', 'Focus', 'italiano', 'Bao Publishing', 'Ogni tanto qualcosa e\' simpatica ufo a parte e l articolo di come combattere uno squalo e\' meraviglioso', '2021-01-13', 1, 5.0, 123, 1);
INSERT INTO `ISPW`.`RIVISTA` (`titolo`, `tipologia`, `autore`, `lingua`, `editore`, `Descrizione`, `dataPubblicazione`, `disp`, `prezzo`, `copieRimanenti`, `id`) VALUES ('Focus Junior', 'MENSILE', 'Focus', 'italiano', 'Bao Publishing', 'arino magari qualche bambino sviluppa interesse per il complottismo', '2021-01-21', 1, 2.0, 1234, 2);
INSERT INTO `ISPW`.`RIVISTA` (`titolo`, `tipologia`, `autore`, `lingua`, `editore`, `Descrizione`, `dataPubblicazione`, `disp`, `prezzo`, `copieRimanenti`, `id`) VALUES ('Tv Sorrisi e canzoni', 'SETTIMANALE', 'Panorama', 'italiano', 'Bao Publishing', 'ok', '2021-02-02', 0, 4.0, 50, 3);
INSERT INTO `ISPW`.`RIVISTA` (`titolo`, `tipologia`, `autore`, `lingua`, `editore`, `Descrizione`, `dataPubblicazione`, `disp`, `prezzo`, `copieRimanenti`, `id`) VALUES ('Rivista A', 'SPORTIVO', 'Bao Publishing', 'italiano', 'Bao Publishing', 'okok', '1970-01-01', 1, 2.0, 121, 4);
INSERT INTO `ISPW`.`RIVISTA` (`titolo`, `tipologia`, `autore`, `lingua`, `editore`, `Descrizione`, `dataPubblicazione`, `disp`, `prezzo`, `copieRimanenti`, `id`) VALUES ('Rivista B', 'SPORTIVO', 'Bao Publishing', 'italiano', 'Bao Publishing', 'testo casuale', '1970-01-01', 1, 2.0, 131, 5);

COMMIT;

